best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/YaleB.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/YaleB.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/YaleB
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.9292307719999998
  std: 0.03014757225156174
metric_f1:
  mean: 0.9278050005550005
  std: 0.031970595605618504
metric_precision:
  mean: 0.9482839105339107
  std: 0.021350857705762897
metric_recall:
  mean: 0.9273809523809524
  std: 0.031432359079122785
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 64
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 6
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
tbwriter_args:
  log_dir: ./logs/YaleB
val_metric_acc:
  mean: 0.6964102719999999
  std: 0.024879860124118792
val_metric_f1:
  mean: 0.6972124578291724
  std: 0.024948215824588085
val_metric_precision:
  mean: 0.7398508938292075
  std: 0.02411124444823525
val_metric_recall:
  mean: 0.6968782388466784
  std: 0.024910781067686318
weight_decay1: 0.01
weight_decay2: 0.0005
