best_trial: 20
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/BBCSports.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/BBCSports.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/BBCSports
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.738104448
  std: 0.04156312903661724
metric_f1:
  mean: 0.7420021409423688
  std: 0.03693082359365421
metric_precision:
  mean: 0.7999103927641852
  std: 0.042477212014675046
metric_recall:
  mean: 0.752197601358322
  std: 0.027897244428148286
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 72
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 16
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/BBCSports
val_metric_acc:
  mean: 0.9344293959999999
  std: 0.041208305610014644
val_metric_f1:
  mean: 0.9417196271770474
  std: 0.03401165988104152
val_metric_precision:
  mean: 0.953937842868797
  std: 0.025029138510464035
val_metric_recall:
  mean: 0.9414090816533409
  std: 0.02802363685169605
weight_decay1: 0.01
weight_decay2: 0.0005
