acc_mean: 0.9361702130000001
acc_std: 0.03560255459571351
best_trial: 20
best_trial_save_dir: best/
dataset_args:
  mat_path: data/BBCSports.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/BBCSports.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/BBCSports
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 72
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 16
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/BBCSports
weight_decay1: 0.01
weight_decay2: 0.0005
