best_trial: 10
best_trial_save_dir: best/
dataset_args:
  mat_path: data/Caltech1017.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/Caltech1017.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Caltech1017
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.387074832
  std: 0.103323008958955
metric_f1:
  mean: 0.3348050851228198
  std: 0.10889080152948337
metric_precision:
  mean: 0.41840264595639776
  std: 0.10766804382767133
metric_recall:
  mean: 0.3823659766937078
  std: 0.10462672550724261
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 72
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 30
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/Caltech1017
val_metric_acc:
  mean: 0.805199698
  std: 0.11197453224778774
val_metric_f1:
  mean: 0.3107414652495154
  std: 0.08976185048934675
val_metric_precision:
  mean: 0.3647366831890373
  std: 0.14373686084024404
val_metric_recall:
  mean: 0.3901958179619414
  std: 0.09604027520081163
weight_decay1: 0.01
weight_decay2: 0.0005
