best_trial: 10
best_trial_save_dir: best/
dataset_args:
  mat_path: data/WebKB_washington.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/WebKB_washington.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/WebKB_washington
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 80
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 4
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/WebKB_washington
val_metric_acc:
  mean: 0.6071244370000001
  std: 0.1720876143631952
val_metric_f1:
  mean: 0.42843798591640897
  std: 0.08325029905149077
val_metric_precision:
  mean: 0.5157538519472149
  std: 0.07924461672925694
val_metric_recall:
  mean: 0.5478360236701343
  std: 0.05633088553915673
weight_decay1: 0.01
weight_decay2: 0.0005
