best_trial: 10
best_trial_save_dir: best/
dataset_args:
  mat_path: data/ALOI.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/ALOI.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ALOI
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.25208549399999997
  std: 0.03250816288085047
metric_f1:
  mean: 0.19576243215716865
  std: 0.03477662592713371
metric_precision:
  mean: 0.25905213365572777
  std: 0.021431480221727882
metric_recall:
  mean: 0.2381397306397306
  std: 0.032712509530260316
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 112
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 36
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/ALOI
val_metric_acc:
  mean: 0.11163568800000001
  std: 0.02711454493916597
val_metric_f1:
  mean: 0.023825696871200768
  std: 0.0144250261857048
val_metric_precision:
  mean: 0.01831951262893089
  std: 0.01655439170234637
val_metric_recall:
  mean: 0.1093760738831615
  std: 0.028128221649484527
weight_decay1: 0.01
weight_decay2: 0.0005
