best_trial: 20
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/ALOI.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/ALOI.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ALOI
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.1986354765
  std: 0.0201346696164127
metric_f1:
  mean: 0.15296793165284395
  std: 0.02407851970115298
metric_precision:
  mean: 0.2220171913684758
  std: 0.04400696192947799
metric_recall:
  mean: 0.19906222378729868
  std: 0.019986859250033958
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 120
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 32
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/ALOI
val_metric_acc:
  mean: 0.100974656
  std: 0.0007797280000000018
val_metric_f1:
  mean: 0.019480452944557344
  std: 0.0045342604435066195
val_metric_precision:
  mean: 0.01587355916186027
  std: 0.02184587923604952
val_metric_recall:
  mean: 0.10004901960784315
  std: 0.0002136715168402193
weight_decay1: 0.01
weight_decay2: 0.0005
