acc_mean: 0.10277777499999999
acc_std: 0.007986704111251084
best_trial: 20
best_trial_save_dir: best/
dataset_args:
  mat_path: data/ALOI.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/ALOI.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ALOI
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 120
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 32
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/ALOI
weight_decay1: 0.01
weight_decay2: 0.0005
