best_trial: 20
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/Wikipedia.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/Wikipedia.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Wikipedia
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.49650985700000005
  std: 0.030256305622663696
metric_f1:
  mean: 0.4433322793924212
  std: 0.03449582406777872
metric_precision:
  mean: 0.4993944509353879
  std: 0.034689921045715714
metric_recall:
  mean: 0.46570334319560114
  std: 0.027352931687339817
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 128
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 16
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/Wikipedia
val_metric_acc:
  mean: 0.6257207920000001
  std: 0.029686520123690753
val_metric_f1:
  mean: 0.5585737718353464
  std: 0.042414443660936635
val_metric_precision:
  mean: 0.6197029988295147
  std: 0.04917895763325017
val_metric_recall:
  mean: 0.5901106444034973
  std: 0.02514741651898799
weight_decay1: 0.01
weight_decay2: 0.0005
