best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/YaleB_F10.mat
  topk: 100
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/YaleB_F10.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/YaleB_F10
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 1.0
  std: 0.0
metric_f1:
  mean: 1.0
  std: 0.0
metric_precision:
  mean: 1.0
  std: 0.0
metric_recall:
  mean: 1.0
  std: 0.0
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 120
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 2
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
tbwriter_args:
  log_dir: ./logs/YaleB_F10
val_metric_acc:
  mean: 0.6637607029999999
  std: 0.0329080877149925
val_metric_f1:
  mean: 0.6654942271187777
  std: 0.030818823813027425
val_metric_precision:
  mean: 0.7238549835471253
  std: 0.01809816772512208
val_metric_recall:
  mean: 0.6645553026341424
  std: 0.03285255820398193
weight_decay1: 0.01
weight_decay2: 0.0005
