best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/Caltech10120.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/Caltech10120.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Caltech10120
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.445606697
  std: 0.15680331637636968
metric_f1:
  mean: 0.41093374974429164
  std: 0.1705407046998801
metric_precision:
  mean: 0.472212799832256
  std: 0.16466441481612332
metric_recall:
  mean: 0.4407894736842105
  std: 0.15644085139610903
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 112
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 4
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/Caltech10120
val_metric_acc:
  mean: 0.606381004
  std: 0.16696226270964798
val_metric_f1:
  mean: 0.34349572191026273
  std: 0.13894921655336245
val_metric_precision:
  mean: 0.3984435541069106
  std: 0.16832442469016798
val_metric_recall:
  mean: 0.3911541183969469
  std: 0.12985486441827035
weight_decay1: 0.01
weight_decay2: 0.0005
