best_trial: 20
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/citeseer.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/citeseer.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/citeseer
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.5921671424999999
  std: 0.010150766844403868
metric_f1:
  mean: 0.556226550325967
  std: 0.010087812097604251
metric_precision:
  mean: 0.6225155492177494
  std: 0.01689164699991306
metric_recall:
  mean: 0.5594791680822956
  std: 0.00987626100436416
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 112
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 2
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/citeseer
val_metric_acc:
  mean: 0.6734667894999999
  std: 0.007882446367982127
val_metric_f1:
  mean: 0.6322268191493301
  std: 0.0077627677804160446
val_metric_precision:
  mean: 0.6993542759878887
  std: 0.02087480030212397
val_metric_recall:
  mean: 0.6349648317384871
  std: 0.00908814242351395
weight_decay1: 0.01
weight_decay2: 0.0005
