best_trial: 10
best_trial_save_dir: best/
dataset_args:
  mat_path: data/Cora.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/Cora.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Cora
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.96999999
  std: 0.007114570686273337
metric_f1:
  mean: 0.970082083647281
  std: 0.007000858931128304
metric_precision:
  mean: 0.971430693830315
  std: 0.006794261616003461
metric_recall:
  mean: 0.9697029719286767
  std: 0.007038483044300445
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 88
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 20
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/Cora
val_metric_acc:
  mean: 0.7914274029999999
  std: 0.007166289259410408
val_metric_f1:
  mean: 0.7774087666304083
  std: 0.006817069582010336
val_metric_precision:
  mean: 0.7839681198596495
  std: 0.008044374731898112
val_metric_recall:
  mean: 0.7935458934451216
  std: 0.005423018989459072
weight_decay1: 0.01
weight_decay2: 0.0005
