acc_mean: 0.7534395560000001
acc_std: 0.011430850302147867
best_trial: 20
best_trial_save_dir: best/
dataset_args:
  mat_path: data/Cora.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/Cora.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Cora
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 104
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 42
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/Cora
weight_decay1: 0.01
weight_decay2: 0.0005
