best_trial: 20
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/Cora.mat
  topk: 10
  train_ratio: 0.05
device: cuda
dfcallback_args:
  df_save_path: ./tables/Cora.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Cora
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.5480761725000001
  std: 0.01361367205811308
metric_f1:
  mean: 0.5278928204062365
  std: 0.011779541597104535
metric_precision:
  mean: 0.5383983360138911
  std: 0.014563822374025837
metric_recall:
  mean: 0.5445032472790301
  std: 0.010802856758323143
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 104
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 42
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
tbwriter_args:
  log_dir: ./logs/Cora
val_metric_acc:
  mean: 0.7559852260000001
  std: 0.010260161311154616
val_metric_f1:
  mean: 0.7436445089728624
  std: 0.011208362732070069
val_metric_precision:
  mean: 0.7919023249536897
  std: 0.033198824025571304
val_metric_recall:
  mean: 0.7542698685739924
  std: 0.01227552739806385
weight_decay1: 0.01
weight_decay2: 0.0005
