best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/MSRCv1_v2.mat
  topk: 20
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/MSRCv1_v2.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/MSRCv1_v2
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.328571437
  std: 0.07514158915280007
metric_f1:
  mean: 0.25468303033520423
  std: 0.08252983465949
metric_precision:
  mean: 0.2954608585858586
  std: 0.09733949642635067
metric_recall:
  mean: 0.30833333333333324
  std: 0.0699426572889676
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 120
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 16
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/MSRCv1_v2
val_metric_acc:
  mean: 0.23227512899999997
  std: 0.06507936275609781
val_metric_f1:
  mean: 0.12400061123255383
  std: 0.05646467066012108
val_metric_precision:
  mean: 0.13085611472050251
  std: 0.05843618414750654
val_metric_recall:
  mean: 0.23815628815628812
  std: 0.06702921385037294
weight_decay1: 0.01
weight_decay2: 0.0005
