best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/ORL_v3.mat
  topk: 4
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/ORL_v3.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/ORL_v3
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.17719298500000003
  std: 0.10996795923996637
metric_f1:
  mean: 0.09081090493569652
  std: 0.0691665081540649
metric_precision:
  mean: 0.09069834367911286
  std: 0.06618410486039712
metric_recall:
  mean: 0.13846153846153844
  std: 0.08245094969647963
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 224
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 8
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/ORL_v3
val_metric_acc:
  mean: 0.11107871969999998
  std: 0.07594122730149723
val_metric_f1:
  mean: 0.057474178133063256
  std: 0.05366621557430741
val_metric_precision:
  mean: 0.058226004124936795
  std: 0.05735565545159582
val_metric_recall:
  mean: 0.11743055555555555
  std: 0.08051435728114001
weight_decay1: 0.01
weight_decay2: 0.0005
