best_trial: 5
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/MITIndoor.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/MITIndoor.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/MITIndoor
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.128505069
  std: 0.014103698076833038
metric_f1:
  mean: 0.11698016524145605
  std: 0.014467690167863017
metric_precision:
  mean: 0.1957292101761381
  std: 0.025873070907512213
metric_recall:
  mean: 0.1281986531986532
  std: 0.012965695632209943
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 96
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 28
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/MITIndoor
val_metric_acc:
  mean: 0.10838342999999999
  std: 0.018423991563472884
val_metric_f1:
  mean: 0.08809588056273791
  std: 0.011353118398770574
val_metric_precision:
  mean: 0.15988323950106326
  std: 0.012462345920761474
val_metric_recall:
  mean: 0.1083421697806457
  std: 0.018325713215747205
weight_decay1: 0.01
weight_decay2: 0.0005
