best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/Mfeat.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/Mfeat.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Mfeat
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.155
  std: 0.02626785107312739
metric_f1:
  mean: 0.10707214401717949
  std: 0.024236367248737657
metric_precision:
  mean: 0.15203637687189225
  std: 0.03845006084996954
metric_recall:
  mean: 0.16492857142857137
  std: 0.02850688145429861
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 96
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 34
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/Mfeat
val_metric_acc:
  mean: 0.1516666664
  std: 0.05682276933839085
val_metric_f1:
  mean: 0.06917986320641074
  std: 0.0533564187420151
val_metric_precision:
  mean: 0.09164241745352555
  std: 0.06283216565033385
val_metric_recall:
  mean: 0.15094916000881037
  std: 0.057180698892382274
weight_decay1: 0.01
weight_decay2: 0.0005
