best_trial: 10
best_trial_save_dir: best/
dataset_args:
  mat_path: data/Mfeat.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/Mfeat.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Mfeat
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: false
epochs: 1500
executions_per_trial: 2
loss_weights: None
max_trials: 125
metric_acc:
  mean: 0.1585
  std: 0.018980252896102306
metric_f1:
  mean: 0.11107787080716199
  std: 0.02553192955067468
metric_precision:
  mean: 0.15368521064743818
  std: 0.022839852825841014
metric_recall:
  mean: 0.15761204481792715
  std: 0.02376420984543004
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 120
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 54
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: false
tbwriter_args:
  log_dir: ./logs/Mfeat
val_metric_acc:
  mean: 0.141833334
  std: 0.04401181912836214
val_metric_f1:
  mean: 0.049390862984997876
  std: 0.02582107778143266
val_metric_precision:
  mean: 0.03214218243910762
  std: 0.019062894131501775
val_metric_recall:
  mean: 0.14067026895014806
  std: 0.04465191039992275
weight_decay1: 0.01
weight_decay2: 0.0005
