best_trial: 10
best_trial_save_dir: temp_result/
dataset_args:
  mat_path: data/Out_Scene.mat
  topk: 10
  train_ratio: 0.1
device: cuda
dfcallback_args:
  df_save_path: ./tables/Out_Scene.csv
earlystop_args:
  checkpoint_dir: ./checkpoint/Out_Scene
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: true
  save_best_only: true
epochs: 1500
executions_per_trial: 5
loss_weights: None
max_trials: 250
metric_acc:
  mean: 0.235447761
  std: 0.07716666661187346
metric_f1:
  mean: 0.17905217343904273
  std: 0.10130560934981886
metric_precision:
  mean: 0.26438529194077975
  std: 0.10852247363953935
metric_recall:
  mean: 0.2320357142857142
  std: 0.08068703386525984
model_args:
  alpha: 0.1
  dropout: 0.5
  hid_dim: 64
  lamda: 0.5
  layerclass: GCNIILayer
  nlayer: 6
model_class_args:
  class_name: GCNII_model
  module_path: models.model
optimizer_args:
  lr: 0.01
optimizer_class_args:
  class_name: Adam
  module_path: torch.optim
quiet: true
tbwriter_args:
  log_dir: ./logs/Out_Scene
val_metric_acc:
  mean: 0.231322317
  std: 0.07478900693702117
val_metric_f1:
  mean: 0.1277319670532869
  std: 0.09807929830343312
val_metric_precision:
  mean: 0.2089123233663918
  std: 0.11901150750073619
val_metric_recall:
  mean: 0.22789744864111058
  std: 0.07787273033907531
weight_decay1: 0.01
weight_decay2: 0.0005
